### ISSUE TITLE
Add a gh-pages branch

### ISSUE THREAD

**Issue by romaricpascal** [tzi/presentation-CssIsAwesome#1]
Looks like it would work out of the box if it was hosted on Github pages. Could be worth adding a gh-pages branch :)

Or add a link to a 5minfork in the readme: http://5minfork.com/tzi/CssIsAwesome

**Comment by tzi** [comment]
I didn't notice this issue!
It was done since: http://tzi.github.io/presentation-CssIsAwesome/

Thanks ;)
